### ISSUE TITLE
CountedSyncMap has a race condition.

### ISSUE THREAD

**Issue by Tillaert** [pions/signaler#4]
### Your environment.
  - Version: c11bee9378791cf0401b004a31c9cf59fa0cbc8c
  - Browser: n/a
  - Other Information -

### What did you do?

https://github.com/pion/signaler/blob/c11bee9378791cf0401b004a31c9cf59fa0cbc8c/internal/room/room.go#L11 has a race conditon.

The sync.Map and the len variable are not controlled by mutex/atomic operation. So they can be modified by different threads independently. During a simultanous add and delete, a non empty room can be destroyed. This seems to be a race condition?

### What did you expect?

No race conditions present.

**Comment by Sean-Der** [comment]
@Tillaert that is an excellent point! You are right, we need to perform transactions. I would change `sync.Map` to just a normal map. Then just put a mutex on the entire structure.

If you have interest in this repo I would love to give you write access! I think it would be great if we had a simple signaler for people to use. We could also extend to do other useful things. I just don't have the bandwidth myself :(
